// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQa7jbfVk4Ey3tlZoioq7mkXCjs0ixuoQ',
    appId: '1:315027536356:web:46304e9e36471704a8aff1',
    messagingSenderId: '315027536356',
    projectId: 'cinetix-kmu',
    authDomain: 'cinetix-kmu.firebaseapp.com',
    storageBucket: 'cinetix-kmu.appspot.com',
    measurementId: 'G-X0405WEWKF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCY312ITt2JGXUmmZUfVLnTE-i_Kog72mA',
    appId: '1:315027536356:android:f32be17cf8a1c6a9a8aff1',
    messagingSenderId: '315027536356',
    projectId: 'cinetix-kmu',
    storageBucket: 'cinetix-kmu.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQb6UXG9oS4JLFs3t-teayvDJeshsYts8',
    appId: '1:315027536356:ios:b990a9ba2be806b8a8aff1',
    messagingSenderId: '315027536356',
    projectId: 'cinetix-kmu',
    storageBucket: 'cinetix-kmu.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQb6UXG9oS4JLFs3t-teayvDJeshsYts8',
    appId: '1:315027536356:ios:b990a9ba2be806b8a8aff1',
    messagingSenderId: '315027536356',
    projectId: 'cinetix-kmu',
    storageBucket: 'cinetix-kmu.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQa7jbfVk4Ey3tlZoioq7mkXCjs0ixuoQ',
    appId: '1:315027536356:web:b48da9e0026c8256a8aff1',
    messagingSenderId: '315027536356',
    projectId: 'cinetix-kmu',
    authDomain: 'cinetix-kmu.firebaseapp.com',
    storageBucket: 'cinetix-kmu.appspot.com',
    measurementId: 'G-TQ4LN2MVM7',
  );
}
